# Generated by Django 3.2.8 on 2021-12-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_asgi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchannel',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='is_connected'),
            preserve_default=False,
        ),
    ]
