# Generated by Django 3.2.8 on 2021-12-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_asgi', '0002_userchannel_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='seen_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicchatmessage',
            name='seen_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
