# Generated by Django 3.2.8 on 2021-12-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_asgi', '0003_auto_20211202_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchannel',
            name='is_connected',
            field=models.BooleanField(default=True, verbose_name='is_connected'),
        ),
    ]
